# Generated by Django 4.0.6 on 2022-07-30 17:19

from django.db import migrations, models
import e_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('other', 'другая'), ('monitors', 'мониторы'), ('processors', 'процессоры'), ('keyboards', 'клавиатуры')], default='other', max_length=30, verbose_name='Категория')),
                ('remainder', models.PositiveIntegerField(validators=[e_shop.models.min_remainder_validator], verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
